/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { LandRegistry__factory } from "./LandRegistry__factory";
export { LandRegistryWithSig__factory } from "./LandRegistryWithSig__factory";
