/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace LandRegistry {
  export type TransferHistoryStruct = {
    from: AddressLike;
    to: AddressLike;
    timestamp: BigNumberish;
    price: BigNumberish;
    documentURI: string;
  };

  export type TransferHistoryStructOutput = [
    from: string,
    to: string,
    timestamp: bigint,
    price: bigint,
    documentURI: string
  ] & {
    from: string;
    to: string;
    timestamp: bigint;
    price: bigint;
    documentURI: string;
  };
}

export interface LandRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "VERIFIER_ROLE"
      | "disputedProperties"
      | "getOwnerProperties"
      | "getPropertyHistory"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "ownerProperties"
      | "pause"
      | "paused"
      | "properties"
      | "propertyHistory"
      | "raiseDispute"
      | "registerProperty"
      | "renounceRole"
      | "resolveDispute"
      | "revokeRole"
      | "supportsInterface"
      | "transferProperty"
      | "unpause"
      | "updateMetadata"
      | "updatePropertyValue"
      | "verifyProperty"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "MetadataUpdated"
      | "Paused"
      | "PropertyDisputed"
      | "PropertyRegistered"
      | "PropertyTransferred"
      | "PropertyValueUpdated"
      | "PropertyVerified"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "VERIFIER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "disputedProperties",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getOwnerProperties",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPropertyHistory",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ownerProperties",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(functionFragment: "properties", values: [string]): string;
  encodeFunctionData(
    functionFragment: "propertyHistory",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "raiseDispute",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "registerProperty",
    values: [string, BigNumberish, string, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "resolveDispute",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferProperty",
    values: [string, AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateMetadata",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePropertyValue",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyProperty",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "VERIFIER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disputedProperties",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOwnerProperties",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPropertyHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "ownerProperties",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "properties", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "propertyHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "raiseDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerProperty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resolveDispute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferProperty",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateMetadata",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePropertyValue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyProperty",
    data: BytesLike
  ): Result;
}

export namespace MetadataUpdatedEvent {
  export type InputTuple = [
    propertyId: string,
    metadataURI: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    propertyId: string,
    metadataURI: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    propertyId: string;
    metadataURI: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PropertyDisputedEvent {
  export type InputTuple = [
    propertyId: string,
    disputedBy: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    propertyId: string,
    disputedBy: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    propertyId: string;
    disputedBy: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PropertyRegisteredEvent {
  export type InputTuple = [
    propertyId: string,
    owner: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    propertyId: string,
    owner: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    propertyId: string;
    owner: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PropertyTransferredEvent {
  export type InputTuple = [
    propertyId: string,
    from: AddressLike,
    to: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    propertyId: string,
    from: string,
    to: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    propertyId: string;
    from: string;
    to: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PropertyValueUpdatedEvent {
  export type InputTuple = [
    propertyId: string,
    newValue: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    propertyId: string,
    newValue: bigint,
    timestamp: bigint
  ];
  export interface OutputObject {
    propertyId: string;
    newValue: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PropertyVerifiedEvent {
  export type InputTuple = [
    propertyId: string,
    verifier: AddressLike,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    propertyId: string,
    verifier: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    propertyId: string;
    verifier: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LandRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): LandRegistry;
  waitForDeployment(): Promise<this>;

  interface: LandRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  VERIFIER_ROLE: TypedContractMethod<[], [string], "view">;

  disputedProperties: TypedContractMethod<[arg0: string], [boolean], "view">;

  getOwnerProperties: TypedContractMethod<
    [owner: AddressLike],
    [string[]],
    "view"
  >;

  getPropertyHistory: TypedContractMethod<
    [propertyId: string],
    [LandRegistry.TransferHistoryStructOutput[]],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  ownerProperties: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  properties: TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, string, bigint, boolean, bigint, string] & {
        propertyId: string;
        owner: string;
        area: bigint;
        location: string;
        value: bigint;
        isVerified: boolean;
        lastUpdated: bigint;
        metadataURI: string;
      }
    ],
    "view"
  >;

  propertyHistory: TypedContractMethod<
    [arg0: string, arg1: BigNumberish],
    [
      [string, string, bigint, bigint, string] & {
        from: string;
        to: string;
        timestamp: bigint;
        price: bigint;
        documentURI: string;
      }
    ],
    "view"
  >;

  raiseDispute: TypedContractMethod<[propertyId: string], [void], "nonpayable">;

  registerProperty: TypedContractMethod<
    [
      propertyId: string,
      area: BigNumberish,
      location: string,
      value: BigNumberish,
      metadataURI: string
    ],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  resolveDispute: TypedContractMethod<
    [propertyId: string],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  transferProperty: TypedContractMethod<
    [
      propertyId: string,
      newOwner: AddressLike,
      price: BigNumberish,
      documentURI: string
    ],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  updateMetadata: TypedContractMethod<
    [propertyId: string, metadataURI: string],
    [void],
    "nonpayable"
  >;

  updatePropertyValue: TypedContractMethod<
    [propertyId: string, newValue: BigNumberish],
    [void],
    "nonpayable"
  >;

  verifyProperty: TypedContractMethod<
    [propertyId: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "VERIFIER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "disputedProperties"
  ): TypedContractMethod<[arg0: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "getOwnerProperties"
  ): TypedContractMethod<[owner: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getPropertyHistory"
  ): TypedContractMethod<
    [propertyId: string],
    [LandRegistry.TransferHistoryStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "ownerProperties"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "properties"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, bigint, string, bigint, boolean, bigint, string] & {
        propertyId: string;
        owner: string;
        area: bigint;
        location: string;
        value: bigint;
        isVerified: boolean;
        lastUpdated: bigint;
        metadataURI: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "propertyHistory"
  ): TypedContractMethod<
    [arg0: string, arg1: BigNumberish],
    [
      [string, string, bigint, bigint, string] & {
        from: string;
        to: string;
        timestamp: bigint;
        price: bigint;
        documentURI: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "raiseDispute"
  ): TypedContractMethod<[propertyId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerProperty"
  ): TypedContractMethod<
    [
      propertyId: string,
      area: BigNumberish,
      location: string,
      value: BigNumberish,
      metadataURI: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "resolveDispute"
  ): TypedContractMethod<[propertyId: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferProperty"
  ): TypedContractMethod<
    [
      propertyId: string,
      newOwner: AddressLike,
      price: BigNumberish,
      documentURI: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateMetadata"
  ): TypedContractMethod<
    [propertyId: string, metadataURI: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updatePropertyValue"
  ): TypedContractMethod<
    [propertyId: string, newValue: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyProperty"
  ): TypedContractMethod<[propertyId: string], [void], "nonpayable">;

  getEvent(
    key: "MetadataUpdated"
  ): TypedContractEvent<
    MetadataUpdatedEvent.InputTuple,
    MetadataUpdatedEvent.OutputTuple,
    MetadataUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PropertyDisputed"
  ): TypedContractEvent<
    PropertyDisputedEvent.InputTuple,
    PropertyDisputedEvent.OutputTuple,
    PropertyDisputedEvent.OutputObject
  >;
  getEvent(
    key: "PropertyRegistered"
  ): TypedContractEvent<
    PropertyRegisteredEvent.InputTuple,
    PropertyRegisteredEvent.OutputTuple,
    PropertyRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "PropertyTransferred"
  ): TypedContractEvent<
    PropertyTransferredEvent.InputTuple,
    PropertyTransferredEvent.OutputTuple,
    PropertyTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PropertyValueUpdated"
  ): TypedContractEvent<
    PropertyValueUpdatedEvent.InputTuple,
    PropertyValueUpdatedEvent.OutputTuple,
    PropertyValueUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "PropertyVerified"
  ): TypedContractEvent<
    PropertyVerifiedEvent.InputTuple,
    PropertyVerifiedEvent.OutputTuple,
    PropertyVerifiedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "MetadataUpdated(string,string,uint256)": TypedContractEvent<
      MetadataUpdatedEvent.InputTuple,
      MetadataUpdatedEvent.OutputTuple,
      MetadataUpdatedEvent.OutputObject
    >;
    MetadataUpdated: TypedContractEvent<
      MetadataUpdatedEvent.InputTuple,
      MetadataUpdatedEvent.OutputTuple,
      MetadataUpdatedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PropertyDisputed(string,address,uint256)": TypedContractEvent<
      PropertyDisputedEvent.InputTuple,
      PropertyDisputedEvent.OutputTuple,
      PropertyDisputedEvent.OutputObject
    >;
    PropertyDisputed: TypedContractEvent<
      PropertyDisputedEvent.InputTuple,
      PropertyDisputedEvent.OutputTuple,
      PropertyDisputedEvent.OutputObject
    >;

    "PropertyRegistered(string,address,uint256)": TypedContractEvent<
      PropertyRegisteredEvent.InputTuple,
      PropertyRegisteredEvent.OutputTuple,
      PropertyRegisteredEvent.OutputObject
    >;
    PropertyRegistered: TypedContractEvent<
      PropertyRegisteredEvent.InputTuple,
      PropertyRegisteredEvent.OutputTuple,
      PropertyRegisteredEvent.OutputObject
    >;

    "PropertyTransferred(string,address,address,uint256)": TypedContractEvent<
      PropertyTransferredEvent.InputTuple,
      PropertyTransferredEvent.OutputTuple,
      PropertyTransferredEvent.OutputObject
    >;
    PropertyTransferred: TypedContractEvent<
      PropertyTransferredEvent.InputTuple,
      PropertyTransferredEvent.OutputTuple,
      PropertyTransferredEvent.OutputObject
    >;

    "PropertyValueUpdated(string,uint256,uint256)": TypedContractEvent<
      PropertyValueUpdatedEvent.InputTuple,
      PropertyValueUpdatedEvent.OutputTuple,
      PropertyValueUpdatedEvent.OutputObject
    >;
    PropertyValueUpdated: TypedContractEvent<
      PropertyValueUpdatedEvent.InputTuple,
      PropertyValueUpdatedEvent.OutputTuple,
      PropertyValueUpdatedEvent.OutputObject
    >;

    "PropertyVerified(string,address,uint256)": TypedContractEvent<
      PropertyVerifiedEvent.InputTuple,
      PropertyVerifiedEvent.OutputTuple,
      PropertyVerifiedEvent.OutputObject
    >;
    PropertyVerified: TypedContractEvent<
      PropertyVerifiedEvent.InputTuple,
      PropertyVerifiedEvent.OutputTuple,
      PropertyVerifiedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
